In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Leitura e exploracão de dados - EDA

In [11]:
df = pd.read_csv("student_lifestyle_db.csv")

In [12]:
df.count()

Student_ID            100000
Age                   100000
Gender                100000
Department            100000
CGPA                  100000
Sleep_Duration        100000
Study_Hours           100000
Social_Media_Hours    100000
Physical_Activity     100000
Stress_Level          100000
Depression            100000
dtype: int64

In [13]:
df.head()

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False
3,1004,21,Male,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,1005,19,Male,Arts,3.14,6.8,2.6,4.3,4,6,False

In [14]:
df.tail()

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
99995,100996,24,Female,Medical,2.02,7.0,0.6,1.4,66,4,False
99996,100997,24,Male,Arts,2.33,5.0,3.6,5.2,103,3,False
99997,100998,24,Female,Engineering,2.23,6.5,5.8,4.1,61,5,False
99998,100999,19,Male,Engineering,3.61,6.1,4.8,4.9,116,4,False
99999,101000,24,Female,Medical,2.10,7.9,3.5,4.0,79,4,False

In [15]:
df.shape

(100000, 11)

In [16]:
df.dtypes

Student_ID              int64
Age                     int64
Gender                    str
Department                str
CGPA                  float64
Sleep_Duration        float64
Study_Hours           float64
Social_Media_Hours    float64
Physical_Activity       int64
Stress_Level            int64
Depression               bool
dtype: object

In [18]:
df.describe()

,Student_ID,Age,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,51000.500000,21.009010,2.898316,6.996425,4.509517,3.503288,74.353180,4.131660
std,28867.657797,2.000382,0.532240,1.498682,1.976076,1.486852,43.366963,1.424151
min,1001.000000,18.000000,1.560000,3.000000,0.000000,0.000000,0.000000,2.000000
25%,26000.750000,19.000000,2.450000,6.000000,3.200000,2.500000,37.000000,3.000000
50%,51000.500000,21.000000,2.900000,7.000000,4.500000,3.500000,74.000000,4.000000
75%,76000.250000,23.000000,3.350000,8.000000,5.800000,4.500000,112.000000,5.000000
max,101000.000000,24.000000,4.000000,12.000000,12.800000,10.000000,149.000000,10.000000

### 1.1 As variaveis gender, department e depression sao categoricas, devemos transforma-las

In [20]:
df[["Gender","Department","Depression"]].head()

   Gender   Department  Depression
0  Female      Science       False
1    Male  Engineering       False
2    Male      Medical       False
3    Male  Engineering       False
4    Male         Arts       False

#### 1.1.1 As variaveis gender e department sao dummies, transformando

In [21]:
df=pd.get_dummies(df,columns=["Gender","Department"],drop_first=True)

In [22]:
df.head()

,Student_ID,Age,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression,Gender_Male,Department_Business,Department_Engineering,Department_Medical,Department_Science
0,1001,22,3.50,7.3,3.3,3.4,114,5,False,False,False,False,False,True
1,1002,20,2.72,5.5,7.2,6.0,142,2,False,True,False,True,False,False
2,1003,20,3.01,5.4,2.3,1.8,137,3,False,True,False,False,True,False
3,1004,21,3.63,8.1,2.0,4.6,130,3,False,True,False,True,False,False
4,1005,19,3.14,6.8,2.6,4.3,4,6,False,True,False,False,False,False

#### 1.1.2 Agora selecionamos as variaveis booleanas e colocamos como inteiras

In [23]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [24]:
df.head()

,Student_ID,Age,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression,Gender_Male,Department_Business,Department_Engineering,Department_Medical,Department_Science
0,1001,22,3.50,7.3,3.3,3.4,114,5,0,0,0,0,0,1
1,1002,20,2.72,5.5,7.2,6.0,142,2,0,1,0,1,0,0
2,1003,20,3.01,5.4,2.3,1.8,137,3,0,1,0,0,1,0
3,1004,21,3.63,8.1,2.0,4.6,130,3,0,1,0,1,0,0
4,1005,19,3.14,6.8,2.6,4.3,4,6,0,1,0,0,0,0

### 1.2 Para analise e modelagem, o id do estudante n eh uma variavel interessante, podemos dropar

In [25]:
df = df.drop("Student_ID", axis=1)

In [26]:
df.head()

,Age,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression,Gender_Male,Department_Business,Department_Engineering,Department_Medical,Department_Science
0,22,3.50,7.3,3.3,3.4,114,5,0,0,0,0,0,1
1,20,2.72,5.5,7.2,6.0,142,2,0,1,0,1,0,0
2,20,3.01,5.4,2.3,1.8,137,3,0,1,0,0,1,0
3,21,3.63,8.1,2.0,4.6,130,3,0,1,0,1,0,0
4,19,3.14,6.8,2.6,4.3,4,6,0,1,0,0,0,0

In [27]:
df.isnull().sum()

Age                       0
CGPA                      0
Sleep_Duration            0
Study_Hours               0
Social_Media_Hours        0
Physical_Activity         0
Stress_Level              0
Depression                0
Gender_Male               0
Department_Business       0
Department_Engineering    0
Department_Medical        0
Department_Science        0
dtype: int64